#!/bin/bash
#
# The check script runs after a learner pressed the "Check" button. The check 
# script is used to validate if the learner solved the challenge. 
#

if ! docker image ls | grep -q "my-service"; then
    fail-message "Couldn't find an image with the name my-service"
    exit 1
fi
