#!/bin/bash
set -euxo pipefail

echo "Running track setup script"

# Wait for the Instruqt host bootstrap to finish.
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Here we are installing the nginx package. The noninteractive setting ensures
# that the apt command won't stop and ask for user input.
apt -y update
DEBIAN_FRONTEND=noninteractive apt -y install nginx

# Remove the default nginx landing page and replace
# it with something more useful.
rm /var/www/html/index.nginx-debian.html
cat >> /var/www/html/index.html <<-EOF
<html>
  <head><title>Meow!</title></head>
  <body>
  <div style="width:800px;margin: 0 auto">
  <!-- BEGIN -->
  <center><img src="http://placekitten.com/640/480"></img></center>
  <center><h2>Meow World!</h2></center>
  <center>Welcome to the Meow World application. Meow! =^._.^=</center>
  <!-- END -->
  </div>
  </body>
</html>
EOF

# Start up the nginx service.
service nginx start
