#!/bin/bash
echo "Running challenge setup script on host container"

# Adjust VSCode settings
mkdir -p /user-data/User
cat > /user-data/User/settings.json <<EOF
{
  "workbench.colorTheme": "Default Dark+"
}
EOF

# Install Node.js
# https://github.com/nodesource/distributions/blob/master/README.md
curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
apt-get install -y nodejs

# Clone the example repository
git clone https://github.com/borodean/typescript-example-app.git /app

# Remove return statements to break the tests
ex +g/return/d -cwq /app/src/sum.ts

# Change directory to the cloned repository and install its dependencies
cd /app
npm ci
