#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the check script"

# regex="(?<=Welcome ).*(?=!)"
# path="/app/src/Greeting.js"

# echo "Checking if script contains '$regex' in '$path'"
# grepIfFileContainsRegex="/helper-scripts/grepIfFileContainsRegex"
# fileContainsRegex=$("$grepIfFileContainsRegex" "$regex" "$path")

# echo $fileContainsRegex

# if [[ $fileContainsRegex == *"*/"* ]];
# then
#   fail-message "It seems like you haven't put you name between 'Welcome' and the '!' mark. Please try it again."
#   exit 1
# else
#   echo "Correct"
#   exit 0
# fi

/app/node_modules/.bin/jest --config ./config/jest.config.js --silent --no-color 2> jestOutput.txt

query="FAIL"
path="./jestOutput.txt"

grepIfFileContainsString="/helper-scripts/grepIfFileContainsString"
fileContainsString=$("$grepIfFileContainsString" "$query" "$path")

if [ "$fileContainsString" -eq 0 ]
then
    echo "Failure: Jest failed." >&2
    fail-message "You almost completed the challenge. Make sure that the prop 'name' is used in the Greeting component."
    exit 1
else
    echo "Success: Jest succeeded."
    exit 0
fi
