#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

if ! docker container ls | grep -q "some-container"; then
    fail-message "Couldn't find a container with the name some-container"
    exit 1
fi

echo "This is the check script"

exit 0
