#!/bin/bash

grep "kubectl get nodes" /root/.bash_history || fail-message "Don't forget to list all the nodes with kubectl get nodes"

grep "token" /root/.bash_history || fail-message "Did you login to the Kubernetes Dashboard using the output from ./token.sh?"