#!/bin/sh
#
# This is a sample setup script. Rename this file to setup-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you setup the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the setup script"

echo "Moving challenge to code-server"

echo "First removing existing src"

rm /app/src/*
cp -rT /code-challenges/fundamentals/children/challenge /app

set-workdir /app
cd /app

# installed globally through Docker, so just link it here locally
npm link jest

npm link react-scripts

sh /helper-scripts/startNodeIfPortOpen

exit 0
