name: 'Instruqt Track Push'
description: 'Force pushes an Instruqt track. Must be in the track directory to run.'
inputs:
  path:
    description: Path to the Instruqt track.
    required: true
runs:
  using: 'composite'
  steps:
  - name: Run track push
    shell: bash
    run: |
      cd ${{ inputs.path }}
      docker run -e INSTRUQT_TOKEN=${{ env.INSTRUQT_TOKEN }} --workdir="/track" --mount type=bind,source="$(pwd)",target=/track instruqt/cli track push --force