#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the check script"

# query="{props.children}"
# path="/app/src/ShoppingCart.js"

# echo "Checking if script contains '$query' in '$path'"
# grepIfFileContainsString="/helper-scripts/grepIfFileContainsString"
# fileContainsString=$("$grepIfFileContainsString" "$query1" "$path")

# if [ "$fileContainsString" -eq 1 ]
# then
#   fail-message "It seems that you didn't make use of 'props.children' in the ShoppingCart component. Please check if you use children properly."
#   exit 1
# else
#   echo "Correct"
#   exit 0
# fi

/app/node_modules/.bin/jest --config ./config/jest.config.js --silent --no-color 2> jestOutput.txt

query="FAIL"
path="./jestOutput.txt"

grepIfFileContainsString="/helper-scripts/grepIfFileContainsString"
fileContainsString=$("$grepIfFileContainsString" "$query" "$path")

if [ "$fileContainsString" -eq 0 ]
then
    echo "Failure: Jest failed." >&2
    fail-message "It seems that the children of the ShoppingCart component aren't being used in the component. Please fix this, to complete the challenge."
    exit 1
else
    echo "Success: Jest succeeded."
    exit 0
fi
