#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
set -euxo pipefail

echo "Creating Compute instance..."

gcloud compute instances create myinstance --zone=europe-west1-b
