version: "3"
virtualmachines:
- name: server
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  machine_type: n1-standard-1
- name: worker1
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server
  machine_type: n1-standard-1
- name: worker2
  image: instruqt/k3s-v1-21-1
  shell: /bin/bash
  environment:
    K3S_CONTROL_PLANE_HOSTNAME: server
  machine_type: n1-standard-1
