#!/bin/bash

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Initialize the home directory with the Dockerfile
mkdir /app
touch /app/Dockerfile
set-workdir /app

# Create the Dockerfile
cat <<EOF >> /app/Dockerfile
FROM nginx
EOF
