#!/bin/bash -l 

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
do
    sleep 1 
done

# Wait for the kubernetes dashboard to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/
do 
    sleep 1
done


TOKEN=$(kubectl -n kubernetes-dashboard describe secret admin-user-token | grep ^token | awk '{ print $2 }')
cat <<EOF > token.sh
echo ""
echo $TOKEN
echo ""
echo "This is your token. Use it to log in to the Kubernetes dashboard in the second tab ^"
EOF
chmod +x token.sh

# Enable bash completion for kubectl
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc
