#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the check script"

query="extends React.Component {"
path="/app/src/Greeting.js"

echo "Checking if script contains class component using '$query' in '$path'"
grepIfFileContainsString="/helper-scripts/grepIfFileContainsString"
fileContainsString=$("$grepIfFileContainsString" "$query" "$path")

if [ "$fileContainsString" -eq 1 ]
then
  fail-message "You're almost there. Make sure you define an class component (extends React.Component). For more help, check the Hint links or the slides via notes."
  exit 1
else
  echo "Correct"
  exit 0
fi
