#!/bin/bash

echo "Checking if the folder: 'instruqt' exists."

if [ -d /root/instruqt ]
then
    echo "The folder 'instruqt' exists!"
else
    fail-message "The folder 'instruqt' doesn't exist!"

    exit 1
fi

exit 0