#!/bin/bash
set -euxo pipefail

echo "Running challenge setup script on host docker-vm"

# Initialize the home directory with the Dockerfile
mkdir /app
touch /app/Dockerfile
set-workdir /app

# Create the Dockerfile
cat <<EOF >> /app/Dockerfile
FROM nginx
EOF
