#!/bin/sh
#
# This is a sample check script. Rename this file to check-$CONTAINER
# (where $container is the name of the container as defined in your config.yml),
# and replace this content with your own script.
#
# This script will be run when you check the challenge.
#
# Remember that the exit code is important. See the documentation
# for more information.
#

echo "This is the check script"

query1="const Greeting = () => {"
query2="const Greeting = (props) => {"
query3="const Greeting = props => {"
query4="const Greeting = () => ("
path="/app/src/Greeting.js"

echo "Checking if script contains arrow function using '$query1' in '$path'"
grepIfFileContainsString="/helper-scripts/grepIfFileContainsString"
fileContainsString1=$("$grepIfFileContainsString" "$query1" "$path")

echo "Checking if script contains arrow function using '$query2' in '$path'"
fileContainsString2=$("$grepIfFileContainsString" "$query2" "$path")

echo "Checking if script contains arrow function using '$query3' in '$path'"
fileContainsString3=$("$grepIfFileContainsString" "$query3" "$path")

echo "Checking if script contains arrow function using '$query4' in '$path'"
fileContainsString4=$("$grepIfFileContainsString" "$query4" "$path")

if [ "$fileContainsString1" -eq 1 ] && [ "$fileContainsString2" -eq 1 ] && [ "$fileContainsString3" -eq 1 ] && [ "$fileContainsString4" -eq 1 ]; then
  fail-message "You're almost there. Make sure you define an arrow function. For more help, check the Hint links or the slides via notes."
  exit 1
else
  echo "Correct"
  exit 0
fi
