name: CD
on: pull_request
env:
  ORGANIZATION_SLUG: templates
  INSTRUQT_TOKEN: ${{ secrets.INSTRUQT_TOKEN }}
jobs:
  deploy-changes:
    name: Deploy changes
    runs-on: ubuntu-latest
    container:
      image: instruqt/cli
      env:
        INSTRUQT_TOKEN: ${{ env.INSTRUQT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Pushing tracks
        run: |
          #!/bin/bash

          for track in */; do
              pushd $track
              echo $track
              instruqt --help
              popd
          done\
